### ISSUE TITLE
Problem with SimpleMathJax rendering on Firefox

### ISSUE THREAD

**Issue by p-i-** [jmnote/SimpleMathJax#1]
Hello!

I've just installed SimpleMathJax and tested it by inserting: `<math>E=mc^2</math>`
 
On Chrome (OSX) it renders correctly.

However, on firefox (OSX) it displays the formula three times: [pic](http://pasteboard.co/2dh0cmGR.png)

The second two renditions seem to be one font size smaller than the first.

Is there any way to fix this?

π

**Comment by RichardMorris** [comment]
I just tried SimpleMathJax on Firefox on OSX and it works fine for me. Maybe there is a conflict with other extensions? 

(I'm Salix alba on stack exchange/wikipedia)
