### ISSUE TITLE
SimpleMathJax does not render in Firefox at times

### ISSUE THREAD

**Issue by noloader** [jmnote/SimpleMathJax#12]
This is kind of unusual and it may be related to another component in our stack. My apologies in advance if that is the case.

The [Crypto++ wiki](https://www.cryptopp.com/wiki) uses SimpleMathJax for math markup on occasion. As an example, here is our [Elliptic Curve Digital Signature Algorithm](https://www.cryptopp.com/wiki/Elliptic_Curve_Digital_Signature_Algorithm) page:

![wiki-1](https://user-images.githubusercontent.com/3538226/36347779-21d896e8-142e-11e8-981f-10a4b1a8744e.png)

Now here is the weird thing... *IF* I click the *Page* tab or the *Read* tab, then the math symbols go missing. *IF* I click the *Reload* button then the math symbols appear again. Below, the tabs are highlighted in blue, the missing symbols are highlighted in red, and the reload is highlighted in green.

![wiki-2](https://user-images.githubusercontent.com/3538226/36337140-ddbaf7a6-135d-11e8-8149-c9863232073a.png)

When the math symbols fail to render it looks like the HTML is present:

![wiki-3](https://user-images.githubusercontent.com/3538226/36337466-067a9ba4-1365-11e8-8729-0d87149e5b46.png)

Our stack includes a CentOS 7 Virtual Machine from GoDaddy. The MediaWiki information can be found at [Special:Version](https://www.cryptopp.com/wiki/Special:Version), and it includes MW 1.30, PHP 7.1 and MySQL 5.5. I keep everything fully patched (the best I can).

The browser is configured to send *Do Not Track* with requests, and it does not accept third party cookies. This may happen on other platforms like Linux and other browsers like Chrome. I don't use browsers like IE or Chrome so I can't say for sure.

I'm not sure where to begin to troubleshoot the issue. If there is a mailing list to discuss issues, then please point it out. I don't like polluting issue trackers with opening discussions of problems.

Any help in learning the cause of the problem would be appreciated.

-----

I think we ruled out the EFF's [HTTPS Everywhere](https://www.eff.org/https-everywhere) at [Issue 14654, mathjax.org may need ruleset updated](https://github.com/EFForg/https-everywhere/issues/14654).

**Comment by noloader** [comment]
This may (or may not) be related. When the math symbols are rendered, I see some fetches related to something called **_`font-woff`_**:

![wiki-5](https://user-images.githubusercontent.com/3538226/36339394-323bf2d8-1392-11e8-8280-7184964a1ee6.png)

However, when the symbols go missing, the same fetches are missing:

![wiki-4](https://user-images.githubusercontent.com/3538226/36339400-746b49ec-1392-11e8-90c6-8c097ce33f21.png)

**Comment by jmnote** [comment]
Thanks for the detailed feedback.
I think the font-woff may or may not a problem.

![screenshot](https://user-images.githubusercontent.com/3538226/36337466-067a9ba4-1365-11e8-8729-0d87149e5b46.png)

Your screenshot image below shows ``<span style='display:none'>``.
The style 'display:none' part has to be removed by the script ( SimpleMathJax/modules/ext.SmjCDN.js:19 ) after MathJax CDN script loaded.

```
MathJax.Hub.Queue(function() { $(".MathJax").parent().show(); });
```
Can you check about this?
The code below could be helpful.
```
MathJax.Hub.Queue(function() { $(".MathJax").parent().show(); console.log('CDN script loaded!!!!'); });
```

**Comment by noloader** [comment]
Thanks @jmnote,

It looks like recent changes has made this issue a full time problem. All the math markup has `<span style='display:none'>`.

> ```
> The style 'display:none' part has to be removed by the script ( SimpleMathJax/modules/ext.SmjCDN.js:19 ) after MathJax CDN script loaded.
> 
> MathJax.Hub.Queue(function() { $(".MathJax").parent().show(); });
> ```
> 
> Can you check about this?

Yes, but I need instructions how to do it. ( Sorry, I am not a web guy).

**Comment by noloader** [comment]
@jmnote,

It looks like the issue is now clear on both machines.

It cleared up about a half hour ago on the Windows machine. A page reload worked as expected.

The Ubuntu machine required me to delete the cache. A page reload did not help.

Sorry about the extra noise.
