### ISSUE TITLE
How to typeset in display instead of inline style

### ISSUE THREAD

**Issue by cglosser** [jmnote/SimpleMathJax#13]
I've got SimpleMathJax running on an internal wiki, and typesetting an equation via

    :<math>
      \frac{\partial^2}{\partial t^2} \nabla \cdot \mathbf{E} = 4 \pi \frac{\partial}{\partial t} \nabla \cdot \mathbf{J}
    </math>

sets the equation on the page in inline mode [inline mode](https://user-images.githubusercontent.com/193990/42053267-1b3e3938-7adf-11e8-8c98-4ff40a6fef86.png) (you can tell by the relatively small derivative symbols). Is there a convenient way to set it in LaTeX's display style instead?

**Comment by nadilo72** [comment]
You could modify `module/ext.SmjLocal.js` (or `module/ext.SmjCDN.js`) like so :

```javascript
 //  tex2jax: { inlineMath: mw.config.get('wgSmjInlineMath') },
     tex2jax: { displayMath: mw.config.get('wgSmjInlineMath') },
     displayAlign: "left",
```

displayAlign is needed because Display Mode is centered by default.

**Comment by jmnote** [comment]
Now, it's configuable.

https://github.com/jmnote/SimpleMathJax/commit/2ea6ca3c0664adf3eb07b8052ff22ec6543247ba
