### ISSUE TITLE
Undefined control sequence

### ISSUE THREAD

**Issue by itaJames** [jmnote/SimpleMathJax#14]
I am getting the following error message "Undefined control sequence" for the following:

\geqslant
\leqslant
\because
\varpropto
\therefore
\implies
\impliedby

I am not sure if this is something I am doing wrong?
I am currently using SimpleMathJax v. 0.73 on MediaWiki 1.31
I have successfully used these terms in the past with the 2015 versions on MediaWiki 1.28

**Comment by jmnote** [comment]
Update your SimpleMathJax, 😅
