### ISSUE TITLE
Problem with numeration of formulas

### ISSUE THREAD

**Issue by GreyWolfling** [jmnote/SimpleMathJax#17]
Thanks a lot for your extension! It works great, but there is a problem with numeration of formulas.
I use Mediawiki 1.31.1. I tried to set a number of the formula and wrote this code:

> <math>
> \begin{equation} t^n-1\ge{n\cdot(t-1)}. \end{equation}
> </math>

But number was absent.  I have found the cause. The extension uses tags "math" for inlineMath. But there are no tags for displayMath. So I added additional tags (dmath) for displayed equations. 

I added new variable (SmjDisplayMath) to extension.json:

> "config": {
> 		"SmjSize": 100,
> 		"SmjUseCDN": true,
> 		"SmjUseChem": true,
> 		"SmjInlineMath": [],
> 		"SmjDisplayMath": []
> 	},

Then I changed SimpleMathJax_body.php. I wrote some code for new parameter SmjDisplayMath. 

> public static function setup( Parser $parser ) {
> 		global $wgOut, $wgSmjUseCDN, $wgSmjSize, $wgSmjUseChem, $wgSmjInlineMath, $wgSmjDisplayMath;
> 
> 		$wgOut->addModules( $wgSmjUseCDN ? 'ext.SmjCDN' : 'ext.SmjLocal' );
> 		$wgOut->addJsConfigVars( 'wgSmjSize', $wgSmjSize );
> 		$wgOut->addJsConfigVars( 'wgSmjUseChem', $wgSmjUseChem );
> 		$wgSmjInlineMath[] = ["[math]","[/math]"];
> 		$wgSmjDisplayMath[] = ["[dmath]","[/dmath]"];
> 		$wgOut->addJsConfigVars( 'wgSmjInlineMath', $wgSmjInlineMath );
> 		$wgOut->addJsConfigVars( 'wgSmjDisplayMath', $wgSmjDisplayMath );
> 		$parser->setHook( 'math', __CLASS__ . '::renderMath' );
> 		$parser->setHook( 'dmath', __CLASS__ . '::renderDMath' );
> 		if( $wgSmjUseChem ) $parser->setHook( 'chem', __CLASS__ . '::renderChem' );
> 	}
> public static function renderDMath($tex, array $args, Parser $parser, PPFrame $frame ) {
> 		$tex = str_replace('\>', '\;', $tex);
> 		$tex = str_replace('<', '\lt ', $tex);
> 		$tex = str_replace('>', '\gt ', $tex);
> 		return self::renderDTex($tex, $parser);
> 	}
> private static function renderDTex($tex, $parser) {
> 		return ["<span style='opacity:0.5'>[dmath]${tex}[/dmath]</span>", 'markerType'=>'nowiki'];
> 	}

And in the file ext.SmjCDN.js I changed several lines:

> tex2jax: { displayMath: mw.config.get('wgSmjDisplayMath'),
> 			inlineMath: mw.config.get('wgSmjInlineMath') }
> MathJax.Hub.Queue(function() { 
> 			$(".MathJax").parent().css('opacity',1);
> 			$(".MathJax_Display").parent().css('opacity',1);
> 		});
> MathJax.Hub.Config({ TeX: { equationNumbers: {autoNumber: "AMS"} } });

This code worked correctly. But I am not a programmer, so my code is not optimal. I think my code is terrible from a programmer's point of view :) May be you can add new tag to the code of your extension? I think that new tag is useful for displaying math.

**Comment by jmnote** [comment]
Update your SimpleMathJax, 😅
