### ISSUE TITLE
Context menu missing

### ISSUE THREAD

**Issue by sm8ps** [jmnote/SimpleMathJax#19]
See https://www.mediawiki.org/wiki/Topic:V4gkf5eepqignt19 for details. 
Suggesting to use that thread for further discussion.

**Comment by sm8ps** [comment]
Here is a copy of the issue as per the provided link: "I have been using SimpleMathJax 0.3 on MW-1.23 where there was a context menu for the MathJax formulae with entries like "Show Math As ...", "Math Settings" etc. Now with version 0.7.3 on MW-1.31 I do not see this anymore and cannot find any way to enable it. Is there something I am missing or has this feature been dropped?"
Anybody know how to enable the context menu? The examples provided by https://www.mathjax.org/#a11y (Accessibility and Reuse) all show a context menu upon right clicking. Especially useful is the ability to magnify a formula.

**Comment by jmnote** [comment]
Now, the context menu is configurable. https://github.com/jmnote/SimpleMathJax/commit/d1f8321b13dacb72d6c8ae7fdf9ce4cf293fc613

**Comment by sm8ps** [comment]
Awesome, thanks for your prompt reaction!
I have added the information to the MW-[extension page](https://www.mediawiki.org/wiki/Extension:SimpleMathJax).
