### ISSUE TITLE
미디어위키 최신버전 사용시 콘솔 메세지

### ISSUE THREAD

**Issue by zlzleking** [jmnote/SimpleMathJax#20]
> Error: "Unknown dependency: ext.SmjCDN.mobile"
>     jQuery 3
>     <anonymous> https://zetawiki.com/wiki/특수:버전:9
>     startUp https://zetawiki.com/w/load.php?debug=false&lang=ko&modules=startup&only=scripts&skin=zetaview:20
>     onload https://zetawiki.com/w/load.php?debug=false&lang=ko&modules=startup&only=scripts&skin=zetaview:21

제타위키나 리브레 위키 등 simplemathjax를 사용하는 위키에서 의존성 오류가 출력됩니다.

**Comment by jmnote** [comment]
https://github.com/jmnote/SimpleMathJax/commit/70aacabe8123efaa16e856c17a4798deb970a98b#diff-ef32f2a18f1fd51247cbaab39dcde592
