### ISSUE TITLE
Missing features/ compartibility problem

### ISSUE THREAD

**Issue by chekanov** [jmnote/SimpleMathJax#21]
Hi,
SimpleMathJax is a great tool. We use it for the math encyclopedia called [HandWiki](https://handwiki.org/wiki/), replacing the server-side math parsing with the client-side "SimpleMathJax". We see some pages where SimpleMathJax failed to parse equations. For example, this page imported from Wikipedia:

[https://handwiki.org/wiki/Kalman_filter]( https://handwiki.org/wiki/Kalman_filter)

has a few yellow boxes "Missing argument for \mathbf". Is it possible to fix this?
There are more problematic pages with equations like this that indicate that SimpleMathJax is 100% replacement for what is used by Wikipedia. But we are not sure how automatically catch such pages  with  SimpleMathJax parsing problems.

**Comment by jmnote** [comment]
The website is not accessible. And I cannot find out what Kalman_filter is.

**Comment by chekanov** [comment]
The web site is working OK:

 https://handwiki.org/wiki/Kalman_filter

The problem is that SimpleMathJax cannot parse correctly some equations. See:   " Missing argument for \mathbf"

**Comment by jmnote** [comment]
The website is accessible. There must be some mistake.
It show 6 "Missing argument for \mathbf". But I cannot access the wikitext of that.

**Comment by chekanov** [comment]
There is another problem for MathJax  for this article:

 https://handwiki.org/wiki/Quantum_field_theory 

"Undefined control sequence \rang"

**Comment by jmnote** [comment]
Can you explain what "\rang" is...? MathJax seems to not support \rang.
Try it on https://www.mathjax.org/#demo

**Comment by chekanov** [comment]
This \rang means \rangle and \lang means \langle. For some reason Wikipedia latex equation engine can understand these symbols:

https://en.wikipedia.org/wiki/Quantum_field_theory

See also:

https://math.berkeley.edu/~gbergman/misc/hacks/langl_rangl.html

best
