### ISSUE TITLE
Extension incompatible with Firefox Native MathML add-on

### ISSUE THREAD

**Issue by happy5214** [jmnote/SimpleMathJax#23]
I am trying to load a set of formulas on https://www.rieselprime.de/ziki/Math_rendering, which uses this package. It loads fine with the base browser configuration (Kubuntu 19.10, Firefox 78), but when loaded using Firefox's Native MathML add-on, it only displays TeX within `[math]` tags. For example, the first row in the large table reads `[math]\dot{a}, \ddot{a}, \acute{a}, \grave{a}[/math]`. The Math MediaWiki extension does not have this problem.

**Comment by jmnote** [comment]
https://github.com/jmnote/SimpleMathJax/blob/d73ad7a522cc0f7a38990179efefc3859eb0b218/SimpleMathJax_body.php#L19

https://github.com/jmnote/SimpleMathJax/blob/d73ad7a522cc0f7a38990179efefc3859eb0b218/SimpleMathJax_body.php#L37-L39

I don't have the environment to reproduce that problem. Possibly, the alternative tags with brackets( [ ] ) can cause the trouble. You can try to replace them to another pairs (workaround). Obviously, we need more options to fix the problem and make sure it works on any enviroments.

**Comment by jmnote** [comment]
Now, SimpleMathJax supports MathJax 3.1.2.
Try again, please.

http://docs.mathjax.org/en/latest/output/mathml.html

**Comment by happy5214** [comment]
It's not actually _my_ wiki, but I know the owner, so I'll point him here.

**Comment by happy5214** [comment]
The updates fixed the problems. This issue can be closed.

**Comment by jmnote** [comment]
Good! Thanks!
