### ISSUE TITLE
Registering handler for ParserFirstCallInit before MediaWiki bootstrap complete was deprecated in MediaWiki 1.35

### ISSUE THREAD

**Issue by lens0021** [jmnote/SimpleMathJax#24]
I encounter a console output:

> PHP Deprecated:  Registering handler for ParserFirstCallInit before MediaWiki bootstrap complete was deprecated in MediaWiki 1.35 [Called from SimpleMathJax::onRegistration in /MY_MW_PATH/extensions/SimpleMathJax/SimpleMathJax_body.php at line 6] in /srv/femiwiki.com/includes/debug/MWDebug.php on line 430

Thanks.

**Comment by jmnote** [comment]
Thanks! I think this will resolve it.

https://github.com/jmnote/SimpleMathJax/commit/c4bd866a637bf1799a12f83346e2a6268c9ef193
