### ISSUE TITLE
compatibility with wikipedia 

### ISSUE THREAD

**Issue by chekanov** [jmnote/SimpleMathJax#25]
Hello,

I've move to the new version of SimpleMathJax (from Oct 18, 2020). It works. As for the previous version, there are some compatibility issues for parsing words-like \N, \R \Mu etc. which are very common in wikipedia. Here is an example https://handwiki.org/wiki/Closure%20operator (red capital N is not parsed)

One solution is to add the following lines:

               $tex = str_replace('\Mu', '\mu', $tex);
                $tex = str_replace('\Q ', '\mathbb{Q} ', $tex);
                $tex = str_replace('\Z ', '\mathbb{Z} ', $tex);
                $tex = str_replace('\0 ', '\mathbb{0} ', $tex);
                $tex = str_replace('\A ', '\mathbb{A} ', $tex);
                $tex = str_replace('\R ', '\mathbb{R} ', $tex);
                $tex = str_replace('\C ', '\mathbb{C} ', $tex);
                $tex = str_replace('\S ', '\mathbb{S} ', $tex);
                $tex = str_replace('\R ', '\mathbb{R} ', $tex);
                $tex = str_replace('\Beta', '\mathbf{B}', $tex);

to  renderMath() function, but it is not very elegant since it requires space after the tag (without it, it will corrupt other latex keys). Unfortunately, spaces after \A \C are not common  in Wikipedia. It would be useful to add some method to parse such symbols.

**Comment by jmnote** [comment]
mediawiki-texvc
https://docs.mathjax.org/en/v2.7-latest/tex.html#n

The begingroup and mediawiki-texvc TeX extensions haven’t been ported to version 3 yet, but should be in the future.
* http://docs.mathjax.org/en/latest/upgrading/v2.html?highlight=texvc#not-yet-ported-to-version-3
* http://docs.mathjax.org/en/latest/upgrading/whats-new-3.0.html?highlight=mediawiki-texvc#tex-input-extensions

**Comment by jmnote** [comment]
resolved! 

https://github.com/jmnote/SimpleMathJax/commit/f4a37981a5a5bcb197d32c02d269d5596e9f9e7c

**Comment by chekanov** [comment]
Thanks. I'm using your latest version 0.8.0 where this was implemented in ext.SimpleMathJax.js - this work.

**Comment by jmnote** [comment]
Good! Thanks!
