### ISSUE TITLE
un-rendered [math] block remains visible after editing page with VisualEditor

### ISSUE THREAD

**Issue by hexmode** [jmnote/SimpleMathJax#29]
When using VisualEditor to render the page, the math block's rendering is changed to
![image](https://user-images.githubusercontent.com/43581/98858506-bcd36c00-242e-11eb-8208-9555065087d4.png)

This is fine, since VE provides the user with a dialog to edit the math if they click on the box.

After saving the page, whether the math is changed or not, the un-rendered grey box of TeX-formatted math remains.

SimpleMathJax should use whatever methods it can (I imagine there is a VE hook somewhere) to re-render the math after a page save.

**Comment by jmnote** [comment]
I'm trying to setup VisualEditor. Can you tell me your configurations (mediawiki, parsoid, restbase)?

**Comment by ClausGra** [comment]
Hi,
I can confirm the mentioned behaviour.

We are using:
- MediaWiki: 1.34.1 (docker pull mediawiki:1.34.1)
- VisualEditor: 0.1.1 (74116a7) 00:02, 24 December 2019
- Parsoid: 0.11 (docker pull thenets/parsoid:0.11)
- SimpleMathJax: 0.8.1

And I configured:
```
# SimpleMathJax
wfLoadExtension( 'SimpleMathJax' );
$wgSmjShowMathManu = true;
$wgSmjUseCDN = false;
```


Best regards
Claus

**Comment by jmnote** [comment]
@ClausGra Thanks for your information!
@hexmode You're right. We need a re-render trigger. So, I tried like this. I hope this works your wiki too.
https://github.com/jmnote/SimpleMathJax/commit/99f32fbc30ad02cc2cc1408c32cad3676e1d43d9

**Comment by jmnote** [comment]
resolved.
https://zetawiki.com/wiki/SimpleMathJax_issue_test
