### ISSUE TITLE
new keyword

### ISSUE THREAD

**Issue by chekanov** [jmnote/SimpleMathJax#31]
Suggest to add

  T: "{\\mathbb{T}}",

in  resources/ext.SimpleMathJax.js to make it consistent with Wikipedia (it was checked on HandwIki)

**Comment by jmnote** [comment]
Thanks. Can you show me some links with that?

**Comment by chekanov** [comment]
Here is an example: https://handwiki.org/wiki/HandWiki:Help/Equations Without this change, the equation like
```
<math>
\P = 28 \> \R=\Q * \T,
\larr \O \rang
</math>
```
Cannot be parsed.

**Comment by jmnote** [comment]
Thanks again. Well... It seems to be a custom setting for Handwiki. The Mediawiki/Wikipedia don't have the macro '\T'.
https://github.com/wikimedia/mathoid/blob/master/test/files/mathjax-texvc/mathjax-texvc.json
I think additional macros should go into the optional settings.
