### ISSUE TITLE
dollar sign is not available

### ISSUE THREAD

**Issue by HDNua** [jmnote/SimpleMathJax#4]
1. 한국인이신 것 같아 한국어로 먼저 질문해봅니다.
원래 MathJax로 $ x^2 + y^2 = z^2 $와 같은 수식을 쓸 수 있는 것으로 아는데,
테스트해본 결과 그게 되지 않아서 <math> 태그로 감싸고 있습니다.
이것이 약간 불편하다고 생각해서, 이 이슈를 해결해주실 수 있는지 궁금합니다.

2. If you are NOT Korean, ignore the first paragraph; I just think that you use my mother tongue.
I thought that MathJax supports dollar sign expression like $ x^2 + y^2 = z^2 $,
but it did not work and I'm wrapping all expressions with <math> tag.
I think it is a little uncomfortable, so I ask you that you can solve this issue.

**Comment by jmnote** [comment]
위키백과와의 호환성을 유지하기 위해 <math></math>만 지원하고 있습니다.

This supports <math></math> tag style only for compatibility with Wikipedia.

**Comment by jmnote** [comment]
현재 버전 v0.8.0 기준으로 $wgSmjExtraInlineMath 설정으로 가능합니다.
